### ISSUE TITLE
add contributor

### ISSUE THREAD

**Issue by linlinlin97** [CausalDM/Causal-Decision-Making#2]
@all-contributors please add @linlinlin97 for code

**Comment by RunzheStat** [comment]
https://github.com/all-contributors please add @linlinlin97 for code

**Comment by linlinlin97** [comment]
@all-contributors
 please add @HengruiCai for code and doc.
 please add @YangXU63 for code and doc.
 please add @rui-song for doc.
 please add @shikailuo for doc.

**Comment by linlinlin97** [comment]
@all-contributors

please add @rui-song for doc.

**Comment by linlinlin97** [comment]
@all-contributors
please add @shikailuo for doc.

**Comment by linlinlin97** [comment]
@allcontributors please add @Xiaodong332 for bug
